export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT";
export const SEARCH_PRODUCT_FAILED = "SEARCH_FAILED";
export const SEARCH_PRODUCT_LOADING = "SEARCH_LOADING";

export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_FAILED = "GET_ALL_PRODUCTS_FAILED";
export const GET_ALL_PRODUCTS_LOADING = "GET_ALL_PRODUCTS_LOADING";